/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    ARow: typeof import('ant-design-vue/es')['Row']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    ATypography: typeof import('ant-design-vue/es')['Typography']
    ATypographyParagraph: typeof import('ant-design-vue/es')['TypographyParagraph']
    ATypographyText: typeof import('ant-design-vue/es')['TypographyText']
    ATypographyTitle: typeof import('ant-design-vue/es')['TypographyTitle']
    CardOperator: typeof import('./src/components/CardOperator.vue')['default']
    CardPanel: typeof import('./src/components/CardPanel.vue')['default']
    copy: typeof import("./src/components/card-implement/ExampleCard2 copy.vue")["default"]
    DataStatistic: typeof import('./src/components/DataStatistic.vue')['default']
    Dialog: typeof import("./src/components/Dialog.vue")["default"]
    EmptyCard: typeof import("./src/components/card-implement/EmptyCard.vue")["default"]
    ExampleCard: typeof import("./src/components/card-implement/ExampleCard.vue")["default"]
    ExampleCard2: typeof import("./src/components/card-implement/ExampleCard2.vue")["default"]
    ExampleCard3: typeof import("./src/components/card-implement/ExampleCard3.vue")["default"]
    ExampleCard4: typeof import("./src/components/card-implement/ExampleCard4.vue")["default"]
    InputDialogProvider: typeof import('./src/components/InputDialogProvider.vue')['default']
    LayoutCard: typeof import('./src/components/LayoutCard.vue')['default']
    NewCardList: typeof import('./src/components/NewCardList/index.vue')['default']
    Params: typeof import('./src/components/NewCardList/params.vue')['default']
    PlaceHolderCard: typeof import('./src/components/PlaceHolderCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
