/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACol: typeof import('ant-design-vue/es')['Col']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    ARow: typeof import('ant-design-vue/es')['Row']
    CardOperator: typeof import('./src/components/CardOperator.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    EmptyCard: typeof import('./src/components/card-implement/EmptyCard.vue')['default']
    ExampleCard: typeof import('./src/components/card-implement/ExampleCard.vue')['default']
    ExampleCard2: typeof import('./src/components/card-implement/ExampleCard2.vue')['default']
    LayoutCard: typeof import('./src/components/cards/LayoutCard.vue')['default']
    NewCardList: typeof import('./src/components/cards/NewCardList.vue')['default']
    PlaceHolderCard: typeof import('./src/components/cards/PlaceHolderCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
